apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-claim
  labels:
    app: vprodb
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: default