services:
   vprodb:
      build:
         context: /home/ubuntu/vprofile-project/DockerFiles/DB
      image: kshitijhatwar/vprofile-db-image
      container_name: vprodb-svc
      ports:
        - "3306:3306"
      volumes:
        - vprodbdata:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=admin123

   mc01:
      image: memcached
      container_name: vpromc-svc
      ports:
        - "11211:11211"

   rmq01:
      image: rabbitmq
      container_name: vprormq-svc
      ports:
        - "5672:5672"
      environment:
        - RABBITMQ_DEFAULT_USER=test
        - RABBITMQ_DEFAULT_PASS=test

   vproapp:
      build:
         context: /home/ubuntu/vprofile-project/DockerFiles/app
      image: kshitijhatwar/vprofile-app-image
      container_name: vproapp
      ports:
        - "8080:8080"
      volumes:
        - vproappdata:/usr/local/tomcat/webapps

   vproweb:
      build:
         context: /home/ubuntu/vprofile-project/DockerFiles/Web
      image: kshitijhatwar/vprofile-web-image
      container_name: vproweb
      ports:
        - "80:80"

volumes:
   vproappdata: {}
   vprodbdata: {}
   
