apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app-svc }}
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30080
  selector:
    app: {{ .Values.appname }}
 
