apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.dbSvc }}"
spec:
  ports:
  - port: 3306
    targetPort: vprodb-port
    protocol: TCP
  selector:
    app: {{ include "db.fullname" . }}
  type: ClusterIP
