apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbSvc }}
spec:
  ports:
  - port: 3306
    targetPort: vprodb-port
    protocol: TCP
  selector:
    app: {{ .Values.dbname }}
  type: ClusterIP
