apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app-svc }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appname }}
  ports:
    - port: 8080          # internal cluster port
      targetPort: 8080    # container port
      nodePort: 30455     # external port on each node
      protocol: TCP
