apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mc-svc }}
spec:
  ports:
  - port: 11211
    targetPort: vpromc-port
    protocol: TCP
  selector:
    app: {{ .Values.mcname }}
  type: ClusterIP
