apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.mc.mcSvc }}"
spec:
  ports:
  - port: 11211
    targetPort: vpromc-port
    protocol: TCP
  selector:
    app: {{ include " mc.fullname" . }}
  type: ClusterIP
