apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rmq.fullname" . }}
  labels:
    app: {{ include "rmq.fullname" . }}
spec:
  replicas: {{ .Values.rmq.replicas }}
  selector:
    matchLabels:
      app: {{ include "rmq.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "rmq.fullname" . }}
    spec:
      containers:
      - name: {{ include "rmq.fullname" . }}
        image: {{ .Values.rmq.image }}
        ports:
        - name: vprormq-port
          containerPort: 5672
        env:
         - name: RABBITMQ_DEFAULT_PASS
           valueFrom:
             secretKeyRef:
               name: app-secret
               key: rmq-pass
         - name: RABBITMQ_DEFAULT_USER
           value: "test"
